security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="milena_scram" password="milena-scram-secret";
ssl.truststore.location=/milena-kafka/generated/ssl/kafka.client.truststore.p12
ssl.truststore.password=milena-local-truststore
ssl.truststore.type=PKCS12
ssl.endpoint.identification.algorithm=https
